apiVersion: v1
kind: ConfigMap

metadata:
  name: payment-mq-config
  namespace: payment-platform

data:
  payment.mqsc: |
    DEFINE QLOCAL(PAYMENT.REQUEST)
    DEFINE QLOCAL(PAYMENT.RESPONSE)
    DEFINE QLOCAL(PAYMENT.RETRY)
    DEFINE QLOCAL(PAYMENT.DLQ)
    DEFINE QLOCAL(AUDIT.LOG)

    DEFINE CHANNEL(PAYMENT.SVRCONN)
    CHLTYPE(SVRCONN)
    TRPTYPE(TCP)