apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: payment-platform

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres

          image: postgres:16

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: paymentdb

            - name: POSTGRES_USER
              value: paymentuser

            - name: POSTGRES_PASSWORD
              value: paymentpass

---
apiVersion: v1
kind: Service

metadata:
  name: postgres-service
  namespace: payment-platform

spec:
  selector:
    app: postgres

  ports:
    - port: 5432
      targetPort: 5432