apiVersion: v1
kind: Service

metadata:
  name: payment-api-service
  namespace: payment-platform

spec:
  selector:
    app: payment-api

  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000

  type: NodePort